# Generated by Django 2.1.1 on 2018-12-02 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=800)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ExcursionTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excursion.Excursion')),
            ],
        ),
    ]
