# Generated by Django 2.1.1 on 2018-12-02 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=500)),
                ('food_type', models.CharField(blank=True, choices=[('breakfast', 'Завтрак'), ('breakfast_and_lunch', 'Завтрак и обед'), ('breakfast_and_diner', 'Завтрак и ужин'), ('all_inclusive', 'Всё включено')], max_length=20)),
                ('people_count', models.SmallIntegerField(default=1)),
                ('cost', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('status', models.CharField(blank=True, choices=[('payment_wait', 'Ожидание оплаты'), ('paid', 'Оплачено')], max_length=15)),
                ('cost', models.IntegerField()),
                ('comment', models.TextField(max_length=200)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Offer')),
            ],
        ),
    ]
