# Generated by Django 2.1.1 on 2018-12-02 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resort', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Hotel'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='resort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resort.Resort'),
        ),
    ]
